version: '3.8'

services:
  # SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./SQLScripts:/docker-entrypoint-initdb.d
    networks:
      - plusgym-network

  # Go API
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=PlusGymProject
    networks:
      - plusgym-network

  # Angular Frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - API_URL=http://localhost:5000
    depends_on:
      - api
    networks:
      - plusgym-network

networks:
  plusgym-network:
    name: plusgym-network
    driver: bridge

volumes:
  sqlserver_data:
